import "./AboutSection.css";
import ReturnToShip from "../../components/ReturnToShip/ReturnToShip";
import BackRocket from "../../components/BackRocket/BackRocket";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";

function AboutSection({ exitSection }) {

    return (
        <div className="section about-section">
            <div className="section-header">
                <h2 className="section-title">About</h2>
                <ReturnToShip exitSection={exitSection} />
                <BackRocket exitSection={exitSection} />
            </div>
            <p className="section-text">Until my second semester of college, I had never written a line of code, and it wasn’t until my seventh semester that I read my first research paper. Within this context, it seems incredibly unlikely that the week after graduating with my bachelor’s degree in computer science, I would board a plane for Tokyo to present my research at one of the world’s largest robotics conferences. I attribute my recent achievements in research to my unorthodox upbringing that centered around engineering and athletics.
            </p>
            <p className="section-text">My father is a mechanical engineer and an unrelenting inventor. With him as my teacher, I had access to various creative machinery and equipment, such as a mill, lathe, bandsaw, kiln, and drill press, as well as endless power and hand tools. I grew up taking things apart and putting them back together—when I was very little I even earned the nickname “the undoer”. When I was 15 I began working on my first car: a classic Mustang with rusted-out floors and a gaping hole where the engine should have been. By the time of my high school graduation, I was my father’s respected partner in his creative endeavors, having restored two classic cars, engine-swapped others, welded art pieces, and turned dead trees from my backyard into beautiful pieces of furniture. It was obvious within my family that I would go on to study mechanical engineering, and like my father, enter the workforce after completing my bachelor’s.
            </p>
            <p className="section-text">I chose to study mechanical engineering at the University of Utah where I felt I had the best chance of swimming collegiately, and, like my sister, father, and grandfather, to be a division-one student athlete. While school was important to me (I maintained a perfect GPA throughout highschool), at the time, athletics comprised the majority of my identity; In high school, I was a two-time state champion, state record holder, and junior national qualifier, all of which I credit to my hard headed determination and grit that my Spartan-like coaches instilled in me over the years. As a testament to these qualities, within two months of stepping on campus, I had earned my spot as a walk-on on the team. 
            </p>
            <p className="section-text">I maintained equilibrium with mechanical engineering and swimming for only a short time. In my second semester, after my first conference championship swim meet, the pandemic began to upset my long drudged-for balance. I was in the middle of a mechatronics class that included an introduction to Matlab and Arduino when classes transitioned online. I missed out on building the ping pong ball-shooting robot, but was fully captivated by the magic of programming. That summer, motivated by my first opportunity to vote in an election and feeling empowered by my peek into the world of software, I sought to build an application for the exchange of political ideas direct from candidate to voter. I began an online web development bootcamp to gain the necessary skills, and in the fall, I switched my major to computer science.
            </p>
            <p className="section-text">That semester, in response to the pandemic, the NCAA gave student athletes the opportunity to temporarily “opt-out” of competition with the advertised ability to resume participation after the season ended. I took this offer, seeing it as a rare opportunity to narrowly focus on building the political application, “Platform”, with my good friend, Jan, in hopes of turning it into an impactful and profitable product. Nearing the end of the spring semester, as Jan and I continued to learn about web and product development, new university-imposed budget cuts required the coaches to reduce the swim team roster. As I hadn’t posted any times for the season, I was among the first to go. I reeled for months from the shock of losing the biggest piece of myself—I felt hollow. Feeling it was all that I could do, I doubled down on entrepreneurship, taking to heart that one must be willing to accept risk and make sacrifices when venturing to build a great product. Eventually, feeling that we were in over our heads, Jan and I abandoned spinning a startup out of Platform.
            </p>
            <p className="section-text">Now in my third undergraduate year, I felt like I was starting over, but without the lightness that filled me as I stepped onto the campus two years prior—as if I was again at the base of an unforgiving climb. I separated myself from my athletic social circle by living alone and engrossing myself in academics, adding physics as a second major. It was then that I was introduced to research through a friend, and I began assisting in the electrochemical study of nuclear materials pyroprocessing. By the end of this position several months later, I was still largely unaware of the purpose of research. I hadn’t read a single scientific paper while in the position, and instead spent my time studying electrochemistry out of textbooks attempting to understand the significance of what I was modestly helping with.
            </p>
            <p className="section-text">At the start of my fourth year, I began a software engineering internship at KBR that would lead to my first conference publication. I was tasked with developing an algorithm that found the optimal schedule of satellite observations from a network of ground-based telescopes for an application akin to space traffic control. I distinctly remember the feeling of pride mixed with amateurishness as I read my first research paper in search of a solution. When I determined that the literature was bare on the subject, my internship advisor suggested I submit my solution to a conference for publication. Over the course of a year, I taught myself how to write a conference paper as I simultaneously iterated dozens of mathematical programming representations of the problem. My paper was accepted, and in March of this year, I presented my solution in the small town of Big Sky, Montana at the IEEE Aerospace Conference.
            </p>
            <p className="section-text">The summer before the final year of my undergraduate degree, I decided to continue my education and research in graduate school. Looking for a new research opportunity, I reached out to my favorite professor, Daniel Drew, whose robotics course I had recently taken. With only months before application deadlines, the prospect of a first-author publication was doubtful (I hadn’t yet submitted my aerospace publication), but regardless, Dan proposed the as-of-yet unstudied phenomenon of the ground effect for ionic thrusters. If all went well, an empirical study would be straightforward, relatively quick to complete, and a significant scientific contribution. Almost immediately, the need for a faster method of data collection was obvious. In response I automated the data collection process by modifying a 3D printer to programmatically adjust the experimental setup with 0.1 millimeter precision. This, in combination with a multiprocessed programming interface I designed to control the lab’s high-voltage power supply, oscilloscope, and load cell, allowed me to run experiments around the clock. After weeks of planning my sleep schedule around experiments, we submitted the paper to the 2024 International Conference on Robotics and Automation (ICRA) with hours to spare. Through graduation I continued to research ionic propulsion, leading to two additional papers that are under review and nearing completion, respectively, on which I led the experimental design. In May of this year, I presented my research at ICRA in Yokohama, Japan, marking the end of my transformative undergraduate degree.
            </p>
            <p className="section-text">Unfortunately, the positive climb to Yokohama was paired with the onset of a complex chronic pain condition. In June of 2022, two months prior to starting my internship at KBR, I developed gastrointestinal symptoms that caused me near-constant pain or discomfort. Physicians prescribed medication and left me without answers, and as time went on, the condition failed to improve. I discovered through my own observations that my symptoms would always flare up after physical activity and reduce after remaining sedentary. This was the kick while I was down, completely severing me from athletics and pushing me into a deep depression that lasted for many months. I retreated into solitude where I allowed my obsessive compulsive disorder to re-fasten its grip on me for the first time since I was a child. I sought relief at any cost, even if it meant spending weeks in an inpatient ward, but the medical system continued to fail me; I applied to become a patient at the Mayo Clinic but was rejected twice. I oscillated between furious and fearful at a rate proportional to my pain while each medical office door took months just to open. I grew cynical and distrustful, and in my darkest of hours, took interest in reading Camus’ Myth of Sisyphus. 
            </p>
            <p className="section-text">The change that followed was gradual and nonlinear, beginning simultaneously with my joining the Drew Research Lab the summer prior to my fifth year of undergrad. Starting with Camus, philosophy captivated my attention and cleared a mental space for the manipulation of difficult ideas. I thought frequently about consciousness, cognition, and the role our minds play in regulating our subjective experiences, which was especially relevant as I struggled to manage my own experiences with pain and discomfort. Reading history through the lens of liberal political philosophy in pair with my own experiences moved me to empathize deeply with those who suffer from health conditions and are met with inadequate care or apathetic physicians. My health improved slowly and reluctantly to a level that has since been manageable, and through the many diagnostic procedures I have undergone, my anxiety surrounding the further decline of my health has largely abated.
            </p>
            <p className="section-text">This condition has been the most influential event of my life, resulting in a burning conviction to develop medical technology that helps millions avoid living in pain and that eases the strain on the overburdened medical system within the United States. Because of my late and almost accidental introduction to research, I have never had much choice in the fields within which I studied. Now, as I move on to highly intentional study in graduate school, I refuse to settle for anything not pointing toward my goals. As a start, I interned for four months at iota Biosciences in Alameda, California, where I was introduced to the fascinating world of biotech. Following this, I learned the best standards in infrastructure as a software engineer at Applied Intuition. Currently, and for the next few years, I will be studying interdisciplinary neuroscience in the Neuro-X master’s program at EPFL in Lausanne, Switzerland.
            </p>
            <div className="contact-lines-container">
                <div style={{ marginRight: "10px" }} className="contact-line">
                    <FontAwesomeIcon className="icon" size="2x" icon={faEnvelope} />
                    <a className="link about-link" target="_blank" rel="noopener noreferrer" href="mailto:nationsgrant@gmail.com">nationsgrant@gmail.com</a>
                </div>
                <div style={{ marginRight: "10px" }} className="contact-line">
                    <FontAwesomeIcon className="icon" size="2x" icon={faLinkedin} />
                    <a className="link about-link" target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/grant-nations/">
                        www.linkedin.com/in/grant-nations
                    </a>
                </div>
                <div className="contact-line">
                    <FontAwesomeIcon className="icon" size="2x" icon={faGithub} />
                    <a className="link about-link" target="_blank" rel="noopener noreferrer" href="https://github.com/grant-nations">github.com/grant-nations</a>
                </div>
            </div>
        </div>
    )
}

export default AboutSection;
